version: '3'
services:
  app:
    image: ghcr.io/netsoc/shhd:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NSJAIL_VERSION: '3.0'
        NETSOC_CLI_VERSION: '0.3.5'
    environment:
      - SHHD_LOG_LEVEL=trace
      - SHHD_SSH_LISTEN_ADDRESS=:2222
      - SHHD_JAIL_NETWORK_INTERFACE=nsjail
    ports:
      - '2222:2222'
    volumes:
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - .:/usr/local/lib/shhd
      - ./config.yaml:/run/config/shhd.yaml:ro
    privileged: true
