version: '3'
services:
  nsjail:
    image: ghcr.io/netsoc/nsjail:3.0
    build:
      context: .
      dockerfile: Dockerfile.nsjail
      args:
        NSJAIL_VERSION: '3.0'

  app:
    image: ghcr.io/netsoc/shhd:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NSJAIL_VERSION: '3.0'
    environment:
      - SHHD_LOG_LEVEL=trace
      - SHHD_SSH_LISTEN_ADDRESS=:2222
    ports:
      - '2222:2222'
    volumes:
      - .:/usr/local/lib/shhd
      - ./config.yaml:/run/config/shhd.yaml:ro
    privileged: true
