ARG NSJAIL_VERSION
FROM ghcr.io/devplayer0/nsjail-alpine:$NSJAIL_VERSION AS nsjail

FROM golang:1.15-alpine
ARG NETSOC_CLI_VERSION

RUN apk --no-cache add git gcc musl-dev

RUN install -d -m 777 /.cache
WORKDIR /usr/local/lib/shhd
VOLUME /usr/local/lib/shhd

COPY tools.go ./
RUN cat tools.go | sed -nr 's|^\t_ "(.+)"$|\1|p' | xargs -tI % go get %

RUN apk --no-cache add libstdc++ libnl3 protobuf iproute2 iptables
COPY --from=nsjail /usr/sbin/nsjail /usr/sbin/nsjail
COPY --from=nsjail /usr/local/sbin/firewall.sh /usr/local/sbin/firewall.sh

RUN apk --no-cache add libc6-compat fish coreutils openssh-client curl nano vim
RUN curl -fLo /usr/local/bin/netsoc "https://github.com/netsoc/cli/releases/download/v${NETSOC_CLI_VERSION}/cli-linux-amd64" && \
    chmod +x /usr/local/bin/netsoc && \
    netsoc completion fish > /etc/fish/completions/netsoc.fish

COPY build.dev.sh /usr/local/bin/build.sh
CMD ["CompileDaemon", "-exclude-dir=.git", \
    "-build=go build -o bin/shhd ./cmd/shhd", "-command=bin/shhd", \
    "-graceful-kill"]
