apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shhd.fullname" . }}
  labels:
    {{- include "shhd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "shhd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "shhd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SHHD_SSH_LISTEN_ADDRESS
              value: ':22'

            - name: SHHD_IAM_TOKEN_FILE
              value: /run/secrets/shhd/iam_token.txt
            - name: SHHD_SSH_HOST_KEY_FILES
              value: /run/secrets/shhd/host_key.pem
          ports:
            - name: ssh
              containerPort: 22
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: ssh
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /run/config
            - name: secrets
              mountPath: /run/secrets/shhd
      volumes:
        - name: config
          configMap:
            name: {{ include "shhd.fullname" . }}
        - name: secrets
          secret:
            secretName: {{ include "shhd.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
