apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shhd.fullname" . }}
  labels:
    {{- include "shhd.labels" . | nindent 4 }}
data:
  iam_token.txt: {{ .Values.secrets.iamToken | b64enc }}
  host_key.pem: {{ .Values.secrets.sshHostKey | b64enc }}
