---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shhd.fullname" . }}
  labels:
    {{- include "shhd.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.spec }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    {{- include "shhd.selectorLabels" . | nindent 4 }}
